### ISSUE TITLE
CocoaPods support 

### ISSUE THREAD

**Issue by RuiAAPeres** [RuiAAPeres/Reactor#15]

**Comment by thebarndog** [comment]
This would be great. Currently my networking stack is uber complex, emulating the same process that Reactor uses but in a much more fragmented way. 

It's really easy to setup Cocoapods too. All you need is a pod spec and then push to trunk.

**Comment by RuiAAPeres** [comment]
@startupthekid we have been prioritising the work on #13. I will take care of this issue ASAP.

**Comment by RuiAAPeres** [comment]
@startupthekid the podspec has been pushed to this repo, but not yet to trunk. I need to wait for a release on RAC's side for Swift 2.2. [Unfortunately it seems I am not able to point a dependency to a specific commit.](https://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of)

[RAC's Swift 2.2 compatibility has been merged](https://github.com/ReactiveCocoa/ReactiveCocoa/commit/81befccd188bf2df9b3df833f7fa67763cb4b04), let's just wait for the release.

**Comment by RuiAAPeres** [comment]
@startupthekid disregard what I said previously, the pod is ready to be used. Let me know if everything is ok!

**Comment by thebarndog** [comment]
Can't wait to test it out!
